export const RSS_FEEDS = [{
        source: '@NintendoAmerica',
        url: 'https://nitter.net/NintendoAmerica/rss'
    }, {
        source: '@IndieWorldNA',
        url: 'https://nitter.net/IndieWorldNA/rss'
    }, {
        source: '@Wario64',
        url: 'https://nitter.net/Wario64/rss'
    }, {
        source: 'Serebii',
        url: 'https://nitter.net/SerebiiNet/rss'
    }, {
        source: '@Nibellion',
        url: 'https://nitter.net/Nibellion/rss'
    }, {
        source: 'Nintendo Life',
        url: 'https://nintendolife.com/feeds/news'
    }, {
        source: 'NWR',
        url: 'https://nintendoworldreport.com/rss/news'
    }, {
        source: 'NE',
        url: 'https://nintendoeverything.com/feed'
    }, {
        source: 'Eurogamer',
        url: 'https://eurogamer.net/?format=rss',
    }, {
        source: 'GoNintendo',
        url: 'https://feedpress.me/gonintendo'
    }, {
        source: 'Vooks',
        url: 'https://vooks.net/feed/'
    }, {
        source: 'Bloomberg',
        url: 'https://bloomberg.com/authors/AUvqMRVAZCw/jason-schreier.rss'
    }, {
        source: 'VGC',
        url: 'https://www.videogameschronicle.com/category/news/feed/'
    }, {
        source: 'IGN',
        url: 'http://feeds.feedburner.com/ign/news'
    }, {
        source: 'Kotaku',
        url: 'https://kotaku.com/rss'
    }, {
        source: 'Polygon',
        url: 'https://www.polygon.com/rss/index.xml'
    }, {
        source: 'GameInformer',
        url: 'https://www.gameinformer.com/news.xml'
    }, {
        source: 'VG247',
        url: 'https://www.vg247.com/feed'
    }, {
        source: 'Install Base',
        url: 'https://www.installbaseforum.com/forums/forums/-/index.rss'
    }, {
        source: 'Gematsu',
        url: 'https://www.gematsu.com/feed'
    }, {
        source: 'MyNintendoNews',
        url: 'https://mynintendonews.com/feed/'
    }, {
        source: 'GameSpot',
        url: 'https://www.gamespot.com/feeds/game-news'
    }, {
        source: 'ComicBook',
        url: 'https://comicbook.com/feed/'
    },
];
